# Generated by Django 3.2.15 on 2022-08-20 23:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.ImageField(blank=True, upload_to=api.models.MyModel.nameFile)),
                ('output_url', models.ImageField(blank=True, upload_to=api.models.MyModel.nameFile)),
            ],
        ),
    ]
